"""13

Revision ID: 236537b0dc3b
Revises: None
Create Date: 2016-08-16 09:25:59.421000

"""

# revision identifiers, used by Alembic.
revision = '236537b0dc3b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
